var manual_site_overrides = {
	"penny-arcade.com": new TextLinkFinder("Back", "Next"),
	"boltcity.com": new TextLinkFinder("previous comic", "next comic"),
	"amazingsuperpowers.com": new TextLinkFinder("<previous", "next>"),
	"theoatmeal.com": new TextLinkFinder(null, "Next Page »"),	// Semi-supported
	"megatokyo.com": new TextLinkFinder("Prev", "Next"),
	"xkcd.com": new TextLinkFinder("< Prev", "Next >"),
	"asofterworld.com": new TextLinkFinder("back", "next"),
	"cad-comic.com": new TextLinkFinder("Back", "Next"),
	"pbfcomics.com": new TextLinkFinder("Older", "Newer"),
	"scarygoround.com": new TextLinkFinder("Previous", "Next"),
	"garfieldminusgarfield.net": new TextLinkFinder("Older Comics", "Newer Comics"),
	"daisyowl.com": new TextLinkFinder("Prev", "Next"),
	"70-seas.com": new TextLinkFinder("‹ Previous", "Next ›"),
	"achewood.com": new TextLinkFinder("«", "»"),
	"asciiartfarts.com": new TextLinkFinder("backward one day", "forward one day"),
	"buttercupfestival.com": new TextLinkFinder("previous", "next"),
	"comics.chickennation.com": new TextLinkFinder("‹ Previous", "Next ›"),
	"doghatesme.com": new TextLinkFinder("older »", "« newer"),
	"pinksnowbunny.com": new TextLinkFinder("< prev ", "next >"),
	"kiwisbybeat.com": new TextLinkFinder("previous", "next"),
	"ghostcarpress.com": new TextLinkFinder("◄ Previous", "Next ►"),
	"firmanproductions.com": new TextLinkFinder("◄ Previous", "Next ►"),
	"studiojfish.com": new TextLinkFinder("PREVIOUS PAGE", "NEXT PAGE"),
	"jerkcity.com": new TextLinkFinder("Previous", "Next"),
	"johnnywander.com": new TextLinkFinder("prev", "next"),
	"monsterkillers.com": new TextLinkFinder("<-", "->"),
	"lr-comic.com": new TextLinkFinder("PREV", "NEXT"),
	"overcompensating.com": new TextLinkFinder("<-", "->"),
	"realcanesugar.cc": new TextLinkFinder("‹ Previous", "Next ›"),	// Contains rel tags, but functions differently than explicit buttons (includes blog posts)
	"willlaren.blogspot.com": new TextLinkFinder("Older Posts", "Newer Posts"),
	"blog.trubbleclub.com": new TextLinkFinder("Older Posts", "Newer Posts"),
	"flickr.com": new TextLinkFinder("← prev", "next →"),
	"rice-boy.com": new TextLinkFinder("back", "forward"),
	"manateepower.com": new TextLinkFinder("Previous", "Next"),	// Contains rel tags, but functions differently than explicit buttons
	"questionduck.smackjeeves.com": new TextLinkFinder("< PREV", "NEXT >"),
	"drawbrandondraw.com": new TextLinkFinder("< previous", "next >"),
	"noncanon.com": new TextLinkFinder("Previous", "Next"),
	"everythingdiescomic.com": new TextLinkFinder("« PREV", "NEXT »"),
	"questionablecontent.net": new TextLinkFinder("Previous", "Next"),
	"sorcery101.net": new TextLinkFinder("‹ Previous", "Next ›"),	// Contains rel tags, but functions differently than explicit buttons

	"samandfuzzy.com": new ImageLinkFinder("imgint/nav_prev.gif", "imgint/nav_next.gif"),
	"whiteninjacomics.com": new ImageLinkFinder("/images/previous.jpg", "/images/next.jpg"),
	"dieselsweeties.com": new ImageLinkFinder("/ximages/prev.gif", "/ximages/next.gif"),
	"feelafraidcomic.com": new ImageLinkFinder("nav_02.png", "nav_04.png"),
	"threewordphrase.com": new ImageLinkFinder("/prevlink.gif", "/nextlink.gif"),
	"doublefine.com": new ImageLinkFinder("/themes/site_themes/sideshow/_i/ads/cmcv/b_prev.gif", "/themes/site_themes/sideshow/_i/ads/cmcv/b_next.gif"),
	"supermegacomics.com": new ImageLinkFinder("bigbuttonprevious.png", "bigbuttonnext.png"),
	"perfectstars.com": new ImageLinkFinder("perfectstars.com/layout/navbar/previous.png", "perfectstars.com/layout/navbar/next.png"),
	"picturesforsadchildren.com": new ImageLinkFinder("images/back.gif", "images/next.gif"),
	"gunnerkrigg.com": new ImageLinkFinder("images/prev_a.jpg", "images/next_a.jpg"),
	"gastrophobia.com": new ImageLinkFinder("pix/prev.gif", "pix/next.gif"),
	"dresdencodak.com": new ImageLinkFinder("http://dresdencodak.com/m_prev.png", "http://dresdencodak.com/m_next.png"),
	"dawnoftimecomics.com": new ImageLinkFinder("images/nav_prev.png", "images/nav_next.png"),
	"awkwardzombie.com": new ImageLinkFinder("images/aznavb2.png", "images/aznavb4.png"),
	"americanelf.com": new ImageLinkFinder("webcomicsnation.com/users/americanelf/buttons_and_logos/previous.gif", "webcomicsnation.com/users/americanelf/buttons_and_logos/next.gif"),
	"gunshowcomic.com": new ImageLinkFinder("menu/small/previous.gif", "menu/small/next.gif"),
	"alienlovespredator.com": new ImageLinkFinder("/images/nav_previous.jpg", "/images/nav_next.jpg"),
	"captainexcelsior.com": new ImageLinkFinder("nav/NAV_previous.png", "nav/NAV_next.png"),
	"explodingdog.com": new ImageLinkFinder(null, new RegExp("/drawing/")),	// Semi-supported
	"phdcomics.com": new ImageLinkFinder("images/prev_button.gif", "images/next_button.gif"),
	"dilbert.com": new ImageLinkFinder("/img/v1/blog/btn.left_arrow.gif", "/img/v1/blog/btn.right_arrow.gif"),
	"sinfest.net": new ImageLinkFinder("images/prev_a.gif", "images/next_a.gif"),
	"harkavagrant.com": new ImageLinkFinder("buttonprevious.png", "buttonnext.png"),
	"viruscomix.com": new ImageLinkFinder("subprevious.gif", "subnext.gif"),
	"plasticbrickautomaton.com": new ImageLinkFinder("images/back.png", "images/next.png"),
	"electricretard.com": new ImageLinkFinder("electricretard.com/images/button_previous_off.png", "electricretard.com/images/button_next_off.png"),
	"manga.clone-army.org": new ImageLinkFinder("previous.gif", "next.gif"),

	"smbc-comics.com": new ImageMapLinkFinder("131,13,216,84", "351,21,425,87"),

	"oglaf.com": new HtmlLinkFinder('<div id="pvs" class="nav_ro">', '<div id="nx" class="nav_ro">'),
	"lefthandedtoons.com": new HtmlLinkFinder('<span class="allthewayleft">Previous Comic</span>', '<span class="allthewayleft">Next Comic</span>'),
	"deadwinter.cc": new HtmlLinkFinder("<span>Previous</span>", "<span>Next</span>"),
}
